version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLE_PATH: vendor/bundle
      - image: cimg/redis:6.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake test

  publish:
    docker:
      - image: cimg/ruby:3.1.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build package
          command: gem build zaikio-jwt_auth.gemspec
      - run:
          name: Push package
          command: |
            VERSION=$(ruby -r "./lib/zaikio/jwt_auth/version.rb" -e "print Zaikio::JWTAuth::VERSION")
            gem push zaikio-jwt_auth-${VERSION}.gem
workflows:
  default:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish:
          context:
            - rubygems-push
          requires: [test]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
